# numpy
파이썬에서 수학적 계산을 쉽게 할 수 있도록 도와주는 라이브러리입니다.

In [1]:
import numpy as np

In [5]:
list = ["A","B","C","D","E"]
list2 = [1,2,3]
array = np.array(["A","B","C","D","E"] )
array

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [4]:
print(array.shape)
print(array.ndim)
print(array.dtype)

# 데이터가 내가 원하는 형식이 맞는지 확인!

(5,)
1
<U1


In [8]:
array2 = np.array([["A", "B", "C"], ["D","E","F"]]) # 2차원이라 바깥에 [] 한 번 더
array2

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [9]:
print(array2.shape)
print(array2.ndim)
print(array2.dtype) #문자형 데이터로 이루어짐

(2, 3)
2
<U1


In [18]:
array3 = np.array(
[
    [["A","B","C"], ["D","E","F"]],
    [["A","B","C"], ["D","E","F"]]
])
array3

#대괄호 갯수가 늘어날 때마다 차원이 늘어난다.

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['A', 'B', 'C'],
        ['D', 'E', 'F']]], dtype='<U1')

In [15]:
print(array3.shape)
print(array3.ndim)
print(array3.dtype) #문자형 데이터로 이루어짐

(3, 3)
2
<U1


In [23]:
array4 = np.array(["1","2","3","4","5"])
print(array4.dtype)

array4 = array4.astype(np.int64) #astype > 원하는 형태로 문자를 바꿔줌
print(array4.dtype)

<U1
int64


In [25]:
arr = np.arange(1,10) # 1부터 10까지의 배열
arr # array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 각각 1개의 컬럼

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[0:3]

array([1, 2, 3])

In [31]:
print(arr > 6) # 6보다 작으면 담아주기
print(arr[arr > 6]) # 그것들 중 true면 담아주기

[False False False False False False  True  True  True]
[7 8 9]


In [ ]:
# 배열 연산
arr1 = 